Fix occasional Android crash on launch
- It always successfully launched on the 2nd try
- Introduced by the RN 71 upgrade (33d05e3)
  - MainActivity.java was converted to MainActivity.kt, and the fix wasn't copied over
  - https://github.com/High5Apps/organize-rn/blob/5395a09/android/app/src/main/java/com/organize/MainActivity.java#L38-L42
- The fix is described in the React Navigation docs
  - https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-a-bare-react-native-project
- To pull the crash logs from Android, use `adb logcat --buffer=crash` as recommended by https://stackoverflow.com/a/46932133/2421313
- Relevant part of the crash logs
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.organize/com.organize.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
...
Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
```